import type {
  ActivityItem,
  Automation,
  AutomationJob,
  Channel,
  ContentIdea,
  ContentTemplate,
  DashboardData,
  DashboardMetric,
  GrowthExperiment,
  PerformancePoint,
  PerformanceSnapshot,
  ScheduleItem,
  ShortVideo,
  TrendTopic,
} from "./types";

const metric = (overrides: Partial<PerformanceSnapshot>): PerformanceSnapshot => ({
  impressions: 0,
  views: 0,
  engagedViews: 0,
  averageViewDurationSeconds: 0,
  averagePercentageViewed: 0,
  viewedVsSwipedAway: 0,
  likes: 0,
  comments: 0,
  shares: 0,
  subscribersGained: 0,
  dislikes: 0,
  notInterested: 0,
  estimatedRevenue: 0,
  ...overrides,
});

export const demoChannel: Channel = {
  id: "channel-seoul-lab",
  name: "1분 지식연구소",
  handle: "@one.minute.lab",
  subscribers: 128_420,
  subscriberDelta: 6_842,
  totalViews: 48_720_000,
  monthlyViews: 3_842_190,
  health: "excellent",
  connected: true,
  timezone: "Asia/Seoul",
  defaultLanguage: "ko-KR",
  lastSyncedAt: "2026-07-13T11:42:00+09:00",
};

export const dashboardMetrics: DashboardMetric[] = [
  { label: "최근 28일 조회수", value: 3_842_190, previousValue: 3_112_840, unit: "number", direction: "up" },
  { label: "평균 시청 유지율", value: 88.4, previousValue: 83.7, unit: "percent", direction: "up" },
  { label: "순 구독자 증가", value: 6_842, previousValue: 5_490, unit: "number", direction: "up" },
  { label: "예상 수익", value: 2_947_600, previousValue: 2_625_100, unit: "currency", direction: "up" },
];

export const weeklyPerformance: PerformancePoint[] = [
  { date: "07-07", views: 392_400, subscribers: 672, averagePercentageViewed: 84.1 },
  { date: "07-08", views: 448_900, subscribers: 781, averagePercentageViewed: 85.7 },
  { date: "07-09", views: 421_300, subscribers: 728, averagePercentageViewed: 87.2 },
  { date: "07-10", views: 536_800, subscribers: 954, averagePercentageViewed: 86.8 },
  { date: "07-11", views: 612_700, subscribers: 1_103, averagePercentageViewed: 89.6 },
  { date: "07-12", views: 728_500, subscribers: 1_284, averagePercentageViewed: 91.2 },
  { date: "07-13", views: 701_590, subscribers: 1_320, averagePercentageViewed: 92.1 },
];

export const demoShorts: ShortVideo[] = [
  {
    id: "short-001",
    title: "엘리베이터 닫힘 버튼의 진짜 비밀",
    topic: "일상 속 숨은 과학",
    hook: "매일 누르던 이 버튼, 사실은 작동하지 않을 수도 있습니다.",
    status: "published",
    durationSeconds: 42,
    publishedAt: "2026-07-12T19:30:00+09:00",
    templateId: "template-fact-pop",
    automationId: "automation-daily-facts",
    score: 94,
    metrics: metric({
      impressions: 1_214_000,
      views: 892_430,
      engagedViews: 821_030,
      averageViewDurationSeconds: 39.1,
      averagePercentageViewed: 93.1,
      viewedVsSwipedAway: 78.6,
      likes: 54_210,
      comments: 2_184,
      shares: 18_420,
      subscribersGained: 3_842,
      dislikes: 312,
      notInterested: 680,
      estimatedRevenue: 684_300,
    }),
    tags: ["생활상식", "과학", "엘리베이터"],
  },
  {
    id: "short-002",
    title: "한국에서 가장 짧은 지하철 구간",
    topic: "도시와 교통",
    hook: "출발하자마자 도착 안내가 나오는 역이 있습니다.",
    status: "published",
    durationSeconds: 38,
    publishedAt: "2026-07-11T12:20:00+09:00",
    templateId: "template-map-story",
    automationId: "automation-daily-facts",
    score: 89,
    metrics: metric({
      impressions: 804_000,
      views: 564_920,
      engagedViews: 502_810,
      averageViewDurationSeconds: 33.4,
      averagePercentageViewed: 87.9,
      viewedVsSwipedAway: 72.8,
      likes: 31_480,
      comments: 1_906,
      shares: 9_840,
      subscribersGained: 2_105,
      dislikes: 284,
      notInterested: 530,
      estimatedRevenue: 421_800,
    }),
    tags: ["지하철", "서울", "교통상식"],
  },
  {
    id: "short-003",
    title: "소름 돋게 정확한 수면 계산법",
    topic: "건강한 습관",
    hook: "8시간을 잤는데도 피곤하다면 시간보다 이 주기를 보세요.",
    status: "published",
    durationSeconds: 47,
    publishedAt: "2026-07-10T21:10:00+09:00",
    templateId: "template-clean-explain",
    automationId: "automation-evening-wellness",
    score: 86,
    metrics: metric({
      impressions: 622_000,
      views: 398_170,
      engagedViews: 350_610,
      averageViewDurationSeconds: 40.3,
      averagePercentageViewed: 85.7,
      viewedVsSwipedAway: 68.4,
      likes: 25_910,
      comments: 1_322,
      shares: 12_610,
      subscribersGained: 1_782,
      dislikes: 410,
      notInterested: 604,
      estimatedRevenue: 304_200,
    }),
    tags: ["수면", "건강", "루틴"],
  },
  {
    id: "short-004",
    title: "편의점 얼음컵이 투명한 이유",
    topic: "일상 속 숨은 과학",
    hook: "집에서 얼린 얼음은 뿌연데 편의점 얼음은 왜 투명할까요?",
    status: "review",
    durationSeconds: 41,
    templateId: "template-fact-pop",
    automationId: "automation-daily-facts",
    score: 91,
    tags: ["편의점", "얼음", "생활과학"],
  },
  {
    id: "short-005",
    title: "1분 만에 이해하는 디지털 원화",
    topic: "테크 브리핑",
    hook: "내 통장의 돈과 디지털 원화는 무엇이 다를까요?",
    status: "scheduled",
    durationSeconds: 52,
    scheduledAt: "2026-07-13T20:40:00+09:00",
    templateId: "template-news-grid",
    automationId: "automation-tech-brief",
    score: 88,
    tags: ["CBDC", "핀테크", "경제"],
  },
  {
    id: "short-006",
    title: "비 오는 날 냄새에는 이름이 있다",
    topic: "말이 되는 과학",
    hook: "우리가 좋아하는 비 냄새를 과학자들은 이렇게 부릅니다.",
    status: "rendering",
    durationSeconds: 39,
    templateId: "template-clean-explain",
    automationId: "automation-daily-facts",
    score: 84,
    tags: ["페트리코", "비", "과학용어"],
  },
];

export const demoAutomations: Automation[] = [
  {
    id: "automation-daily-facts",
    name: "매일 한입 상식",
    description: "트렌드를 탐색해 사실 검증, 대본, 음성, 영상, 검수까지 한 번에 처리합니다.",
    status: "active",
    cadence: "매일 12:20 · 19:30",
    nextRunAt: "2026-07-13T18:00:00+09:00",
    lastRunAt: "2026-07-13T10:00:00+09:00",
    runsThisMonth: 25,
    successRate: 96.8,
    dailyLimit: 2,
    steps: [
      { id: "discover", label: "트렌드 탐색", description: "채널 적합도와 포화도를 함께 평가", enabled: true, order: 1, averageDurationSeconds: 38, successRate: 99.2 },
      { id: "verify", label: "출처 교차 검증", description: "신뢰 가능한 출처 두 곳 이상 확인", enabled: true, order: 2, averageDurationSeconds: 64, successRate: 98.1 },
      { id: "script", label: "쇼츠 대본 생성", description: "3초 훅과 장면별 내레이션 구성", enabled: true, order: 3, averageDurationSeconds: 22, successRate: 99.5 },
      { id: "render", label: "음성·영상 렌더", description: "브랜드 템플릿과 자동 자막 적용", enabled: true, order: 4, averageDurationSeconds: 184, successRate: 94.7 },
      { id: "quality", label: "품질·정책 검수", description: "저작권, 반복 콘텐츠, 발음, 자막 검사", enabled: true, order: 5, averageDurationSeconds: 41, successRate: 97.4 },
      { id: "publish", label: "예약 게시", description: "예측 성과가 높은 시간대에 예약", enabled: true, order: 6, averageDurationSeconds: 12, successRate: 99.7 },
    ],
  },
  {
    id: "automation-tech-brief",
    name: "오늘의 테크 1분",
    description: "공식 발표와 신뢰도 높은 매체만 바탕으로 기술 뉴스를 쉽게 설명합니다.",
    status: "active",
    cadence: "평일 20:40",
    nextRunAt: "2026-07-14T17:30:00+09:00",
    lastRunAt: "2026-07-11T17:30:00+09:00",
    runsThisMonth: 9,
    successRate: 93.4,
    dailyLimit: 1,
    steps: [
      { id: "source", label: "공식 소스 수집", description: "발표문과 원문 링크 우선", enabled: true, order: 1, averageDurationSeconds: 51, successRate: 98.8 },
      { id: "script", label: "핵심 요약", description: "전문 용어를 일상어로 변환", enabled: true, order: 2, averageDurationSeconds: 29, successRate: 97.3 },
      { id: "render", label: "브리핑 렌더", description: "뉴스형 모션 템플릿 적용", enabled: true, order: 3, averageDurationSeconds: 231, successRate: 91.6 },
      { id: "review", label: "팩트·정책 검수", description: "날짜, 수치, 인용, 권리 확인", enabled: true, order: 4, averageDurationSeconds: 72, successRate: 99.1 },
    ],
  },
  {
    id: "automation-evening-wellness",
    name: "퇴근길 건강 루틴",
    description: "과장된 의학 표현을 제외하고 실천 가능한 생활 습관을 제작합니다.",
    status: "needs_attention",
    cadence: "화·목 21:10",
    nextRunAt: "2026-07-14T18:30:00+09:00",
    lastRunAt: "2026-07-10T18:30:00+09:00",
    runsThisMonth: 4,
    successRate: 87.5,
    dailyLimit: 1,
    steps: [
      { id: "research", label: "근거 자료 탐색", description: "공공기관·학술 자료 우선", enabled: true, order: 1, averageDurationSeconds: 118, successRate: 92.4 },
      { id: "script", label: "주의 문구 포함 대본", description: "진단이나 치료로 오인되지 않게 구성", enabled: true, order: 2, averageDurationSeconds: 37, successRate: 96.8 },
      { id: "review", label: "사람 검토", description: "건강 콘텐츠는 게시 전 승인 필수", enabled: true, order: 3, averageDurationSeconds: 420, successRate: 89.2 },
    ],
  },
];

export const demoJobs: AutomationJob[] = [
  { id: "job-1038", automationId: "automation-daily-facts", shortId: "short-006", title: "비 오는 날 냄새에는 이름이 있다", status: "running", progress: 68, currentStep: "음성·영상 렌더", createdAt: "2026-07-13T11:31:00+09:00" },
  { id: "job-1037", automationId: "automation-daily-facts", shortId: "short-004", title: "편의점 얼음컵이 투명한 이유", status: "completed", progress: 100, currentStep: "사람 검토 대기", createdAt: "2026-07-13T10:02:00+09:00", completedAt: "2026-07-13T10:08:00+09:00" },
  { id: "job-1036", automationId: "automation-tech-brief", shortId: "short-005", title: "1분 만에 이해하는 디지털 원화", status: "completed", progress: 100, currentStep: "예약 게시 완료", createdAt: "2026-07-11T17:30:00+09:00", completedAt: "2026-07-11T17:38:00+09:00" },
];

export const demoTemplates: ContentTemplate[] = [
  { id: "template-fact-pop", name: "팩트 팝", category: "상식", description: "강한 첫 문장과 대형 키워드로 빠르게 몰입시키는 템플릿", accent: "#7C3AED", aspectRatio: "9:16", estimatedDurationSeconds: 42, usageCount: 38, averageViewRate: 76.8, averageRetention: 91.3, enabled: true },
  { id: "template-clean-explain", name: "클린 익스플레이너", category: "교육", description: "차분한 내레이션과 도식으로 개념을 단계별로 설명", accent: "#0EA5E9", aspectRatio: "9:16", estimatedDurationSeconds: 48, usageCount: 24, averageViewRate: 69.4, averageRetention: 86.2, enabled: true },
  { id: "template-map-story", name: "맵 스토리", category: "여행·도시", description: "지도 확대와 경로 애니메이션에 최적화된 템플릿", accent: "#10B981", aspectRatio: "9:16", estimatedDurationSeconds: 40, usageCount: 17, averageViewRate: 72.1, averageRetention: 88.7, enabled: true },
  { id: "template-news-grid", name: "뉴스 그리드", category: "테크 브리핑", description: "출처와 핵심 수치를 선명하게 보여주는 뉴스형 템플릿", accent: "#F97316", aspectRatio: "9:16", estimatedDurationSeconds: 52, usageCount: 12, averageViewRate: 65.8, averageRetention: 82.9, enabled: true },
];

export const demoIdeas: ContentIdea[] = [
  { id: "idea-201", title: "비행기 창문에 작은 구멍이 있는 이유", angle: "안전장치가 고장 난 흔적처럼 보이지만 압력 조절을 돕는 구조", source: "트렌드 탐색 + 항공사 기술 자료", keywords: ["비행기", "창문", "숨은기능"], trendScore: 96, competition: "medium", expectedViewRange: [420_000, 880_000], createdAt: "2026-07-13T09:20:00+09:00", selected: true },
  { id: "idea-202", title: "카드 결제 1초 동안 벌어지는 일", angle: "단말기부터 승인까지 데이터가 오가는 여정을 초 단위로 시각화", source: "검색 급상승 + 금융결제원 자료", keywords: ["카드결제", "핀테크", "1초"], trendScore: 91, competition: "low", expectedViewRange: [310_000, 650_000], createdAt: "2026-07-13T09:22:00+09:00", selected: false },
  { id: "idea-203", title: "선풍기 날개는 왜 홀수일까", angle: "소음과 진동을 줄이는 설계 원리로 여름 계절성을 공략", source: "계절 트렌드 + 제조사 기술 블로그", keywords: ["선풍기", "여름", "디자인"], trendScore: 88, competition: "medium", expectedViewRange: [280_000, 590_000], createdAt: "2026-07-13T09:25:00+09:00", selected: false },
  { id: "idea-204", title: "한강 다리는 왜 모두 모양이 다를까", angle: "지형, 배의 통행, 건설 시기가 만든 서로 다른 구조", source: "댓글 요청 + 서울기록원", keywords: ["한강", "다리", "서울"], trendScore: 83, competition: "low", expectedViewRange: [230_000, 510_000], createdAt: "2026-07-13T09:31:00+09:00", selected: false },
];

export const demoSchedule: ScheduleItem[] = [
  { id: "schedule-501", shortId: "short-005", title: "1분 만에 이해하는 디지털 원화", scheduledAt: "2026-07-13T20:40:00+09:00", status: "ready", recommendedSlot: true },
  { id: "schedule-502", shortId: "short-004", title: "편의점 얼음컵이 투명한 이유", scheduledAt: "2026-07-14T12:20:00+09:00", status: "planned", recommendedSlot: true },
  { id: "schedule-503", shortId: "short-006", title: "비 오는 날 냄새에는 이름이 있다", scheduledAt: "2026-07-14T19:30:00+09:00", status: "planned", recommendedSlot: false },
];

export const demoExperiments: GrowthExperiment[] = [
  {
    id: "experiment-hook-question",
    name: "질문형 훅 → 반전 선언형 훅",
    hypothesis: "첫 1.5초에 익숙한 믿음을 뒤집으면 스와이프 이탈이 줄어든다.",
    dimension: "hook",
    status: "ready",
    candidateStatus: "candidate",
    riskLevel: "low",
    startedAt: "2026-07-09T09:00:00+09:00",
    evaluationHours: 96,
    control: {
      id: "control-hook-a",
      name: "기존 질문형",
      description: "여러분은 왜 그런지 알고 계셨나요?",
      snapshot: metric({ impressions: 42_000, views: 29_820, engagedViews: 26_340, averageViewDurationSeconds: 35.2, averagePercentageViewed: 84.2, viewedVsSwipedAway: 71, likes: 1_910, comments: 128, shares: 510, subscribersGained: 174, dislikes: 28, notInterested: 83, estimatedRevenue: 21_400 }),
    },
    candidate: {
      id: "candidate-hook-b",
      name: "반전 선언형",
      description: "매일 믿었던 이 상식, 사실은 정반대입니다.",
      snapshot: metric({ impressions: 41_600, views: 32_860, engagedViews: 30_020, averageViewDurationSeconds: 38.9, averagePercentageViewed: 92.6, viewedVsSwipedAway: 79, likes: 2_680, comments: 194, shares: 890, subscribersGained: 286, dislikes: 22, notInterested: 61, estimatedRevenue: 25_800 }),
    },
    safety: { policyWarnings: 0, copyrightClaims: 0, failedRenders: 0, manualReviewPassed: true, reusedContentRisk: 0.08 },
  },
  {
    id: "experiment-caption-density",
    name: "자막 밀도 3단어 → 6단어",
    hypothesis: "한 화면의 문맥을 늘리면 무음 시청자의 이해도가 높아진다.",
    dimension: "caption",
    status: "running",
    candidateStatus: "testing",
    riskLevel: "medium",
    startedAt: "2026-07-12T10:00:00+09:00",
    evaluationHours: 25,
    control: {
      id: "control-caption-a",
      name: "짧은 자막",
      description: "화면당 핵심 단어 2~3개",
      snapshot: metric({ impressions: 4_820, views: 3_410, engagedViews: 3_050, averageViewDurationSeconds: 34.1, averagePercentageViewed: 86.4, viewedVsSwipedAway: 70.7, likes: 216, comments: 12, shares: 51, subscribersGained: 19, dislikes: 4, notInterested: 10, estimatedRevenue: 2_420 }),
    },
    candidate: {
      id: "candidate-caption-b",
      name: "문맥형 자막",
      description: "화면당 의미 단위 5~6개",
      snapshot: metric({ impressions: 4_760, views: 3_462, engagedViews: 3_128, averageViewDurationSeconds: 35.8, averagePercentageViewed: 88.9, viewedVsSwipedAway: 72.7, likes: 231, comments: 16, shares: 58, subscribersGained: 23, dislikes: 6, notInterested: 13, estimatedRevenue: 2_510 }),
    },
    safety: { policyWarnings: 0, copyrightClaims: 0, failedRenders: 0, manualReviewPassed: true, reusedContentRisk: 0.1 },
  },
];

export const demoTrends: TrendTopic[] = [
  { id: "trend-1", keyword: "폭염 행동요령", category: "생활", score: 98, direction: "up", change: 42, source: "YouTube 검색" },
  { id: "trend-2", keyword: "디지털 원화", category: "테크·경제", score: 93, direction: "up", change: 31, source: "Google Trends" },
  { id: "trend-3", keyword: "장마 냄새", category: "과학", score: 89, direction: "up", change: 26, source: "채널 댓글" },
  { id: "trend-4", keyword: "수면 부채", category: "건강", score: 82, direction: "stable", change: 3, source: "YouTube 검색" },
  { id: "trend-5", keyword: "지하철 상식", category: "도시", score: 76, direction: "down", change: -8, source: "Shorts 피드" },
];

export const demoActivities: ActivityItem[] = [
  { id: "activity-1", type: "milestone", title: "주간 조회수 400만 돌파", description: "지난주보다 22.7% 빠르게 도달했습니다.", occurredAt: "2026-07-13T11:18:00+09:00", tone: "success" },
  { id: "activity-2", type: "automation", title: "영상 1개가 검수 단계에 도착", description: "편의점 얼음컵이 투명한 이유 · 정책 검사 통과", occurredAt: "2026-07-13T10:08:00+09:00", tone: "info" },
  { id: "activity-3", type: "experiment", title: "훅 실험 승격 준비 완료", description: "반전 선언형 훅이 종합 점수와 안전 기준을 통과했습니다.", occurredAt: "2026-07-13T09:42:00+09:00", tone: "success" },
  { id: "activity-4", type: "alert", title: "건강 루틴 자동화 확인 필요", description: "두 번째 출처 확인이 지연되어 다음 실행 전 검토가 필요합니다.", occurredAt: "2026-07-12T21:20:00+09:00", tone: "warning" },
  { id: "activity-5", type: "publish", title: "엘리베이터 영상 게시 완료", description: "초기 16시간 조회수 89만 · 예상 범위 상단 돌파", occurredAt: "2026-07-12T19:30:00+09:00", tone: "success" },
];

export const dashboardData: DashboardData = {
  channel: demoChannel,
  metrics: dashboardMetrics,
  weeklyPerformance,
  shorts: demoShorts,
  automations: demoAutomations,
  jobs: demoJobs,
  templates: demoTemplates,
  ideas: demoIdeas,
  schedule: demoSchedule,
  experiments: demoExperiments,
  trends: demoTrends,
  activities: demoActivities,
};

export const demoData = dashboardData;
