"use client";

import { useState } from "react";
import { ArrowRight, CalendarClock, Check, ChevronDown, CircleAlert, Clock3, FileSearch, MoreHorizontal, Play, Plus, Radio, RefreshCw, ShieldCheck, Sparkles, TestTube2, WandSparkles, Workflow, X, Zap } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";

const initialRecipes = [
  { id: 1, name: "새 YouTube 영상 → 쇼츠 6개", source: "@Junlee Lab 새 업로드", cadence: "새 영상 감지 시", success: 96, last: "오늘 09:42", next: "새 영상 대기", active: true, color: "violet" },
  { id: 2, name: "주 3회 AI 트렌드 브리핑", source: "AI·생산성 트렌드 주제", cadence: "월·수·금 10:00", success: 91, last: "금요일 10:03", next: "수요일 10:00", active: true, color: "teal" },
  { id: 3, name: "상위 20% 클립 자동 예약", source: "품질 88점 이상", cadence: "매일 19:30 슬롯", success: 100, last: "어제 19:31", next: "오늘 19:30", active: true, color: "orange" },
  { id: 4, name: "오래된 영상 리마스터", source: "조회수 상위 롱폼", cadence: "매월 첫째 주", success: 84, last: "7월 1일", next: "8월 1일", active: false, color: "blue" },
];

export function AutomationsPage() {
  const [recipes, setRecipes] = useState(initialRecipes); const [builder, setBuilder] = useState(false); const [tested, setTested] = useState(false);
  const toggle = (id: number, value: boolean) => setRecipes((items) => items.map((item) => item.id === id ? { ...item, active: value } : item));
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-[28px] font-bold tracking-tight">자동화</h1><p className="mt-1 text-sm text-muted-foreground">반복 작업은 레시피에 맡기고, 최종 통제권은 직접 유지하세요.</p></div><Button onClick={() => setBuilder(true)}><Plus /> 자동화 만들기</Button></div>
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="실행 중" value="3" detail="모두 정상" color="text-success" /><Stat label="이번 달 실행" value="48" detail="성공 45 · 검토 3" color="text-primary" /><Stat label="절약한 시간" value="16.4h" detail="지난달보다 +4.2h" color="text-info" /></div>
    <Card className="overflow-hidden"><CardHeader><div><CardTitle>자동화 레시피</CardTitle><CardDescription>소스에서 게시와 학습까지 이어지는 작업 흐름입니다.</CardDescription></div><Button variant="secondary" size="sm"><RefreshCw /> 실행 기록</Button></CardHeader><CardContent className="space-y-3">{recipes.map((item) => <div key={item.id} className="grid gap-4 rounded-xl border border-border bg-background/35 p-4 transition hover:border-primary/25 md:grid-cols-[minmax(220px,1.2fr)_minmax(300px,1.6fr)_180px_80px] md:items-center"><div className="flex items-center gap-3"><div className={cn("grid size-10 shrink-0 place-items-center rounded-xl", item.color === "violet" ? "bg-primary/15 text-primary" : item.color === "teal" ? "bg-[#2dd4bf]/10 text-[#2dd4bf]" : item.color === "orange" ? "bg-warning/10 text-warning" : "bg-info/10 text-info")}><Workflow className="size-4" /></div><div><p className="text-sm font-semibold">{item.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.cadence}</p></div></div><div className="flex items-center gap-2 overflow-hidden text-[10px]"><span className="max-w-40 truncate rounded-lg bg-secondary px-2.5 py-2 text-muted-foreground">{item.source}</span><ArrowRight className="size-3 shrink-0 text-muted-foreground" /><span className="rounded-lg bg-secondary px-2.5 py-2">생성</span><ArrowRight className="size-3 shrink-0 text-muted-foreground" /><span className="rounded-lg bg-secondary px-2.5 py-2">검토</span><ArrowRight className="size-3 shrink-0 text-muted-foreground" /><span className="rounded-lg bg-secondary px-2.5 py-2 text-info">YouTube</span></div><div><div className="flex items-center justify-between text-[10px]"><span className="text-muted-foreground">성공률</span><span className="font-mono font-semibold">{item.success}%</span></div><Progress value={item.success} className="mt-1.5" indicatorClassName={item.success > 90 ? "bg-success" : "bg-warning"} /><p className="mt-1.5 text-[9px] text-muted-foreground">다음: {item.next}</p></div><div className="flex items-center justify-end gap-2"><Switch checked={item.active} onCheckedChange={(value) => toggle(item.id, value)} aria-label={`${item.name} 켜기`} /><Button variant="ghost" size="icon"><MoreHorizontal /></Button></div></div>)}</CardContent></Card>
    <section className="grid gap-4 md:grid-cols-2"><Card><CardHeader><div><CardTitle>안전 가드레일</CardTitle><CardDescription>자동화가 멈추고 검토를 요청하는 조건입니다.</CardDescription></div><ShieldCheck className="size-4 text-success" /></CardHeader><CardContent className="space-y-2 text-xs">{[["정책 위험","중간 이상이면 항상 검토"],["원본 유사도","최근 30개와 78% 이상이면 재생성"],["일일 게시 한도","채널별 최대 2개"],["신규 레시피","첫 3회는 자동 공개 금지"]].map(([label,value]) => <div key={label} className="flex items-center justify-between rounded-xl bg-background/45 p-3"><span className="text-muted-foreground">{label}</span><span className="font-semibold">{value}</span></div>)}</CardContent></Card><Card><CardHeader><div><CardTitle>최근 실행</CardTitle><CardDescription>실패한 단계부터 다시 시작할 수 있습니다.</CardDescription></div><Badge variant="success">정상</Badge></CardHeader><CardContent className="space-y-2">{[[Check,"렌더 및 품질 검사 완료","오늘 09:42","text-success"],[Clock3,"분석 데이터 동기화 대기","오늘 08:10","text-info"],[CircleAlert,"음원 권리 확인으로 보류","어제 19:18","text-warning"]].map(([Icon,title,time,color]) => { const I = Icon as typeof Check; return <div key={String(title)} className="flex items-center gap-3 rounded-xl bg-background/45 p-3"><I className={`size-4 ${color}`} /><div className="flex-1"><p className="text-xs font-semibold">{String(title)}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{String(time)}</p></div><ChevronDown className="size-3.5 text-muted-foreground" /></div>; })}</CardContent></Card></section>
    {builder && <div className="fixed inset-0 z-[60] bg-black/65 p-3 backdrop-blur-sm" onMouseDown={() => setBuilder(false)}><div className="mx-auto mt-[4vh] max-h-[92vh] max-w-3xl overflow-auto rounded-2xl border border-border bg-card shadow-2xl" onMouseDown={(e) => e.stopPropagation()}><div className="sticky top-0 z-10 flex items-center justify-between border-b border-border bg-card p-5"><div><h2 className="text-lg font-bold">자동화 레시피 만들기</h2><p className="mt-1 text-xs text-muted-foreground">복잡한 노드 대신 검증된 6단계로 설정합니다.</p></div><Button variant="ghost" size="icon" onClick={() => setBuilder(false)}><X /></Button></div><div className="space-y-3 p-5">{[
      [Radio,"트리거","@Junlee Lab에 새 영상이 공개되면","연결됨"],[FileSearch,"생성","하이라이트 6개 · 25~45초","설정됨"],[WandSparkles,"스타일","Junlee Dark · 임팩트 자막","설정됨"],[ShieldCheck,"품질 기준","88점 이상 · 정책 위험 낮음","보호됨"],[CalendarClock,"게시","월·수·금 19:30 · 일 최대 2개","승인 후"],[Sparkles,"학습","성과 기반 훅 실험 · 자동 승격 없음","안전 모드"],
    ].map(([Icon,title,desc,status], index) => { const I = Icon as typeof Radio; return <button key={String(title)} className="flex w-full items-center gap-4 rounded-xl border border-border bg-background/35 p-4 text-left transition hover:border-primary/35"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><I className="size-4" /></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-xs font-semibold"><span className="font-mono text-[9px] text-muted-foreground">0{index+1}</span>{String(title)}</span><span className="mt-1 block truncate text-[11px] text-muted-foreground">{String(desc)}</span></span><Badge variant={index === 3 ? "success" : index === 4 ? "warning" : "violet"}>{String(status)}</Badge><ChevronDown className="size-4 text-muted-foreground" /></button>; })}
      <div className="rounded-xl border border-info/15 bg-info/[.05] p-4"><p className="flex items-center gap-2 text-xs font-semibold text-info"><TestTube2 className="size-4" /> 실제 게시 없이 먼저 시험해 보세요</p><p className="mt-1.5 text-[10px] leading-4 text-muted-foreground">드라이런은 소스 접근, 생성 비용, 품질 기준과 예약 충돌만 확인합니다.</p></div>
    </div><div className="sticky bottom-0 flex items-center justify-between border-t border-border bg-card p-5"><Button variant="secondary" onClick={() => setTested(true)}>{tested ? <><Check /> 테스트 통과</> : <><Play /> 테스트 실행</>}</Button><div className="flex gap-2"><Button variant="ghost" onClick={() => setBuilder(false)}>취소</Button><Button onClick={() => setBuilder(false)}><Zap /> 자동화 저장</Button></div></div></div></div>}
  </div>;
}

function Stat({ label, value, detail, color }: { label: string; value: string; detail: string; color: string }) { return <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><div className="mt-2 flex items-end justify-between"><p className={`tabular text-2xl font-bold ${color}`}>{value}</p><p className="text-[10px] text-muted-foreground">{detail}</p></div></CardContent></Card>; }
