"use client";

import { useState } from "react";
import { Check, ChevronDown, Copy, Play, Save, ShieldCheck, Sparkles, Type, Volume2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";

const colors = ["#FFE453", "#7C5CFF", "#2DD4BF", "#FF4D6D", "#FFFFFF"];
export function BrandPage() {
  const [accent, setAccent] = useState(colors[0]); const [preset, setPreset] = useState("임팩트"); const [saved, setSaved] = useState(false); const [watermark, setWatermark] = useState(true);
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-[28px] font-bold tracking-tight">브랜드 키트</h1><p className="mt-1 text-sm text-muted-foreground">한 번 설정하면 모든 쇼츠에 일관된 룩과 보이스가 적용됩니다.</p></div><Button onClick={()=>{setSaved(true);window.setTimeout(()=>setSaved(false),2200)}}>{saved?<><Check/>저장됨</>:<><Save/>변경사항 저장</>}</Button></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-4"><Card><CardHeader><div><CardTitle>브랜드 프로필</CardTitle><CardDescription>워크스페이스의 기본 로고와 시각 정체성</CardDescription></div><Badge variant="success">v4 활성</Badge></CardHeader><CardContent className="grid gap-5 md:grid-cols-[180px_1fr]"><button className="flex aspect-square flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-background/40 hover:border-primary/40"><div className="grid size-12 place-items-center rounded-2xl bg-primary text-xl font-black">JL</div><span className="mt-3 text-xs font-semibold">로고 교체</span><span className="mt-1 text-[9px] text-muted-foreground">SVG 또는 PNG</span></button><div className="space-y-4"><label><span className="mb-2 block text-xs font-semibold">브랜드 이름</span><input defaultValue="Junlee Lab" className="h-10 w-full rounded-[10px] border border-input bg-background px-3 text-sm outline-none focus:border-primary" /></label><label><span className="mb-2 block text-xs font-semibold">한 줄 소개</span><input defaultValue="AI와 생산성을 가장 쉽게 설명합니다" className="h-10 w-full rounded-[10px] border border-input bg-background px-3 text-sm outline-none focus:border-primary" /></label><div><span className="mb-2 block text-xs font-semibold">강조 색상</span><div className="flex gap-2">{colors.map((color)=><button key={color} onClick={()=>setAccent(color)} className={cn("grid size-9 place-items-center rounded-full border-2 border-card ring-1",accent===color?"ring-primary ring-offset-2 ring-offset-card":"ring-border")} style={{backgroundColor:color}} aria-label={`강조색 ${color}`}>{accent===color&&<Check className="size-3 text-black"/>}</button>)}</div></div></div></CardContent></Card>
      <Card><CardHeader><div><CardTitle>자막 시스템</CardTitle><CardDescription>한국어 가독성과 안전영역을 우선한 프리셋</CardDescription></div><Type className="size-4 text-muted-foreground" /></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["임팩트","미니멀","뉴스","스토리"].map((item,index)=><button key={item} onClick={()=>setPreset(item)} className={cn("relative aspect-[4/3] overflow-hidden rounded-xl border bg-[#0d0f14] p-3",preset===item?"border-primary ring-1 ring-primary/25":"border-border")}><div className="absolute inset-x-2 bottom-3 text-center text-sm font-black"><span style={index===0?{backgroundColor:accent,color:"#000"}:{}} className={cn("px-1",index===1&&"font-medium",index===2&&"border-l-2 border-info pl-2")}>{item} 자막</span></div>{preset===item&&<span className="absolute right-2 top-2 grid size-5 place-items-center rounded-full bg-primary"><Check className="size-3"/></span>}</button>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><label><span className="mb-2 block text-[10px] font-semibold text-muted-foreground">폰트</span><button className="flex h-10 w-full items-center justify-between rounded-[10px] border border-input bg-background px-3 text-xs">Pretendard ExtraBold <ChevronDown className="size-3"/></button></label><label><span className="mb-2 block text-[10px] font-semibold text-muted-foreground">한 줄 최대 글자</span><input defaultValue="15자" className="h-10 w-full rounded-[10px] border border-input bg-background px-3 text-xs" /></label><label><span className="mb-2 block text-[10px] font-semibold text-muted-foreground">위치</span><button className="flex h-10 w-full items-center justify-between rounded-[10px] border border-input bg-background px-3 text-xs">하단 28% <ChevronDown className="size-3"/></button></label></div></CardContent></Card>
      <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><div><CardTitle>보이스 & 오디오</CardTitle><CardDescription>발음 사전과 믹스 기준</CardDescription></div><Volume2 className="size-4 text-muted-foreground"/></CardHeader><CardContent className="space-y-2"><Setting label="기본 보이스" value="Joon · 한국어 차분함"/><Setting label="말하기 속도" value="1.05×"/><Setting label="배경음 라우드니스" value="-24 LUFS"/><Setting label="발음 사전" value="고유명사 18개"/></CardContent></Card><Card><CardHeader><div><CardTitle>권리와 안전</CardTitle><CardDescription>모든 산출물에 적용되는 기본 규칙</CardDescription></div><ShieldCheck className="size-4 text-success"/></CardHeader><CardContent className="space-y-2"><Setting label="워터마크" value={watermark?"항상 표시":"표시 안 함"} action={()=>setWatermark(!watermark)}/><Setting label="합성 콘텐츠" value="매번 확인"/><Setting label="음악 출처" value="권리 확인 자산만"/><Setting label="자산 출처 장부" value="자동 기록"/></CardContent></Card></div>
    </div><aside className="xl:sticky xl:top-[88px] xl:self-start"><Card className="overflow-hidden"><CardHeader><div><CardTitle>실시간 미리보기</CardTitle><CardDescription>현재 브랜드 규칙으로 렌더링됩니다.</CardDescription></div><Badge variant="violet">9:16</Badge></CardHeader><CardContent><div className="safe-area relative mx-auto aspect-[9/16] w-[240px] overflow-hidden rounded-2xl bg-[radial-gradient(circle_at_70%_20%,rgba(45,212,191,.35),transparent_28%),linear-gradient(145deg,#32237d,#0d0f14_68%)] shadow-2xl"><div className="absolute left-4 top-4 flex items-center gap-2 text-[9px]"><span className="grid size-6 place-items-center rounded-lg bg-primary font-black">JL</span><span>JUNLEE LAB</span></div><div className="absolute inset-x-5 bottom-[28%] text-center text-xl font-black leading-7">질문이 바뀌면<br/><span className="rounded px-1.5 text-black" style={{backgroundColor:accent}}>결과도 달라집니다</span></div>{watermark&&<span className="absolute bottom-5 right-4 text-[8px] text-white/45">@Junlee Lab</span>}<button className="absolute inset-0 grid place-items-center" aria-label="브랜드 미리보기 재생"><span className="grid size-11 place-items-center rounded-full bg-black/35 opacity-0 transition hover:opacity-100"><Play className="size-4 fill-white"/></span></button></div><div className="mt-4 rounded-xl bg-background/50 p-3 text-[10px]"><div className="flex items-center justify-between"><span className="text-muted-foreground">프리셋</span><span className="font-semibold">{preset}</span></div><div className="mt-2 flex items-center justify-between"><span className="text-muted-foreground">안전영역</span><span className="flex items-center gap-1 text-success"><Check className="size-3"/>통과</span></div><div className="mt-2 flex items-center justify-between"><span className="text-muted-foreground">브랜드 버전</span><span className="font-mono">v4</span></div></div><Button variant="secondary" className="mt-4 w-full"><Copy/>프리셋 복제</Button></CardContent></Card><div className="mt-3 rounded-xl border border-info/15 bg-info/[.04] p-4"><p className="flex items-center gap-2 text-xs font-semibold text-info"><Sparkles className="size-4"/>성과 기반 제안</p><p className="mt-2 text-[10px] leading-4 text-muted-foreground">노란 강조색이 보라색보다 완주율이 3.1% 높았어요. 아직 자동 반영하지 않았습니다.</p></div></aside></div>
  </div>;
}
function Setting({label,value,action}:{label:string;value:string;action?:()=>void}) { return <button onClick={action} className="flex w-full items-center justify-between rounded-xl bg-background/45 p-3 text-left"><span className="text-[10px] text-muted-foreground">{label}</span><span className="text-[10px] font-semibold">{value}</span></button>; }
