"use client";

import { useState } from "react";
import { Check, ChevronLeft, ChevronRight, Clock3, GripVertical, Plus, Sparkles, Tv } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";

type ScheduleItem = { id: number; title: string; day: number; time: string; status: "scheduled" | "review" | "published"; color: string };
const days = [["월","13"],["화","14"],["수","15"],["목","16"],["금","17"],["토","18"],["일","19"]];
const slots = ["09:00", "12:00", "15:00", "18:00", "19:30", "21:00"];
const initial: ScheduleItem[] = [
  { id:1,title:"생산성을 높이는 아침 루틴",day:0,time:"12:00",status:"published",color:"bg-success" },
  { id:2,title:"AI 도구 3가지",day:0,time:"19:30",status:"scheduled",color:"bg-primary" },
  { id:3,title:"몰입을 만드는 질문",day:1,time:"12:00",status:"scheduled",color:"bg-info" },
  { id:4,title:"퇴근 후 10분 루틴",day:3,time:"18:00",status:"scheduled",color:"bg-primary" },
  { id:5,title:"아이디어를 콘텐츠로",day:4,time:"21:00",status:"review",color:"bg-warning" },
];
const unscheduled = [{id:20,title:"대체되지 않는 사람의 공통점",score:94,color:"from-[#5847dd] to-[#22194d]"},{id:21,title:"메모를 성과로 바꾸는 법",score:89,color:"from-[#237056] to-[#112d24]"},{id:22,title:"AI 시대의 질문 공식",score:87,color:"from-[#a35030] to-[#3c2017]"}];

export function CalendarPage() {
  const [items, setItems] = useState(initial); const [tray, setTray] = useState(unscheduled); const [dragging, setDragging] = useState<number | null>(null); const [scheduledToast, setScheduledToast] = useState(false);
  function drop(day: number, time: string) { if (dragging == null) return; const pending = tray.find((item) => item.id === dragging); if (pending) { setItems((old) => [...old, { id: pending.id, title: pending.title, day, time, status:"scheduled", color:"bg-primary" }]); setTray((old) => old.filter((item) => item.id !== dragging)); setScheduledToast(true); window.setTimeout(() => setScheduledToast(false), 2600); } setDragging(null); }
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-[28px] font-bold tracking-tight">콘텐츠 캘린더</h1><p className="mt-1 text-sm text-muted-foreground">성과가 좋은 시간대를 찾아 채널별 게시 흐름을 균형 있게 유지합니다.</p></div><Button><Plus /> 일정 추가</Button></div>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card p-3"><div className="flex items-center gap-1"><Button variant="ghost" size="icon"><ChevronLeft /></Button><Button variant="ghost" size="icon"><ChevronRight /></Button><Button variant="secondary" size="sm">오늘</Button><p className="ml-2 text-sm font-bold">2026년 7월 13일–19일</p></div><div className="flex items-center gap-2"><Badge variant="success"><Tv className="size-3" /> Junlee Lab</Badge><div className="rounded-lg border border-border p-0.5"><button className="rounded-md bg-secondary px-3 py-1.5 text-xs font-semibold">주</button><button className="px-3 py-1.5 text-xs text-muted-foreground">월</button></div></div></div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_280px]">
      <Card className="min-w-0 overflow-hidden"><div className="overflow-x-auto"><div className="min-w-[820px]"><div className="grid grid-cols-[62px_repeat(7,1fr)] border-b border-border bg-background/30"><div /><>{days.map(([day,date], index) => <div key={day} className={cn("border-l border-border p-3 text-center", index === 0 && "bg-primary/[.04]")}><p className="text-[10px] text-muted-foreground">{day}</p><p className={cn("mx-auto mt-1 grid size-7 place-items-center rounded-full text-sm font-bold", index === 0 && "bg-primary text-white")}>{date}</p>{index === 2 && <p className="mt-1 text-[9px] text-primary">최적</p>}</div>)}</></div><div className="relative">{slots.map((time) => <div key={time} className="grid min-h-[100px] grid-cols-[62px_repeat(7,1fr)] border-b border-border/70"><div className="p-2 text-right font-mono text-[9px] text-muted-foreground">{time}</div>{days.map((_, day) => { const event = items.find((item) => item.day === day && item.time === time); const optimal = (day === 2 && time === "19:30") || (day === 5 && time === "12:00"); return <div key={`${day}-${time}`} onDragOver={(e) => e.preventDefault()} onDrop={() => drop(day,time)} className={cn("relative border-l border-border/70 p-1.5 transition", dragging && "hover:bg-primary/[.08]", optimal && !event && "bg-primary/[.025]")}>{event ? <button className={cn("h-full w-full rounded-lg border p-2 text-left transition hover:brightness-110", event.status === "published" ? "border-success/20 bg-success/[.07]" : event.status === "review" ? "border-warning/20 bg-warning/[.07]" : "border-primary/20 bg-primary/[.07]")}><span className="flex items-center gap-1.5 text-[9px]"><span className={cn("size-1.5 rounded-full", event.color)} />{event.time}<span className="ml-auto">{event.status === "published" ? <Check className="size-2.5 text-success" /> : <Clock3 className="size-2.5 text-muted-foreground" />}</span></span><span className="mt-1.5 line-clamp-2 block text-[10px] font-semibold leading-4">{event.title}</span><span className="mt-1 block text-[8px] text-muted-foreground">@Junlee Lab</span></button> : optimal ? <button onClick={() => setScheduledToast(true)} className="absolute inset-2 flex flex-col items-center justify-center rounded-lg border border-dashed border-primary/30 text-primary"><Sparkles className="size-3" /><span className="mt-1 text-[8px] font-semibold">추천 시간</span></button> : null}</div>; })}</div>)}<div className="pointer-events-none absolute left-[62px] right-0 top-[366px] flex items-center"><span className="-ml-1 size-2 rounded-full bg-destructive" /><span className="h-px flex-1 bg-destructive/60" /></div></div></div></div></Card>
      <aside className="space-y-4"><Card><CardHeader><div><CardTitle>예약되지 않은 쇼츠</CardTitle><CardDescription>카드를 캘린더 슬롯으로 끌어 놓으세요.</CardDescription></div><Badge variant="neutral">{tray.length}</Badge></CardHeader><CardContent className="space-y-2">{tray.length ? tray.map((item) => <article key={item.id} draggable onDragStart={() => setDragging(item.id)} onDragEnd={() => setDragging(null)} className="flex cursor-grab items-center gap-2 rounded-xl border border-border bg-background/40 p-2 active:cursor-grabbing"><GripVertical className="size-3 shrink-0 text-muted-foreground" /><div className={`aspect-[9/12] w-10 shrink-0 rounded-lg bg-gradient-to-br ${item.color}`} /><div className="min-w-0 flex-1"><p className="line-clamp-2 text-[10px] font-semibold leading-4">{item.title}</p><Badge variant="success" className="mt-1">품질 {item.score}</Badge></div></article>) : <div className="py-8 text-center"><Check className="mx-auto size-5 text-success" /><p className="mt-2 text-xs font-semibold">모두 예약했어요</p></div>}</CardContent></Card><Card className="border-primary/20 bg-primary/[.04]"><CardContent className="p-4"><div className="flex items-center gap-2 text-xs font-semibold text-primary"><Sparkles className="size-4" /> 이번 주 추천</div><p className="mt-3 text-sm font-bold leading-5">수요일 19:30 슬롯이 가장 좋아요.</p><p className="mt-2 text-[10px] leading-4 text-muted-foreground">최근 8주 기준 평균 조회수가 다른 시간보다 21% 높았습니다.</p><Button variant="secondary" size="sm" className="mt-3 w-full">추천대로 자동 배치</Button></CardContent></Card></aside>
    </div>
    {scheduledToast && <div className="fixed bottom-20 right-5 z-50 flex items-center gap-3 rounded-xl border border-success/20 bg-card p-4 shadow-2xl lg:bottom-6"><div className="grid size-8 place-items-center rounded-full bg-success/10 text-success"><Check className="size-4" /></div><div><p className="text-xs font-semibold">예약 완료</p><p className="mt-0.5 text-[10px] text-muted-foreground">선택한 시간에 공개됩니다.</p></div></div>}
  </div>;
}
