"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, CalendarClock, Captions, Check, ChevronDown, CircleAlert, Download, Filter, LayoutGrid, List, Maximize2, MoreHorizontal, Music2, Pause, Play, Search, Trash2, Undo2, Volume2, WandSparkles, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { cn } from "@/lib/utils";

const videos = [
  { id: 1, title: "AI 시대에도 대체되지 않는 사람들의 공통점", hook: "결국 살아남는 사람은 질문이 다릅니다", score: 94, status: "검토 대기", duration: "0:34", gradient: "from-[#5646d9] via-[#312371] to-[#11131a]", risk: "안전" },
  { id: 2, title: "생산성을 2배 높이는 10분 루틴", hook: "퇴근 직전 딱 10분만 투자하세요", score: 91, status: "검토 대기", duration: "0:42", gradient: "from-[#08757c] via-[#124a51] to-[#0d1c22]", risk: "음원 확인" },
  { id: 3, title: "지금 배워야 할 AI 도구 3가지", hook: "이 3개만 알아도 일하는 속도가 달라집니다", score: 88, status: "예약됨", duration: "0:31", gradient: "from-[#b65932] via-[#6d321f] to-[#1a1210]", risk: "안전" },
  { id: 4, title: "메모를 성과로 바꾸는 가장 쉬운 방법", hook: "메모를 쌓기만 하면 아무것도 달라지지 않아요", score: 86, status: "게시됨", duration: "0:37", gradient: "from-[#34785b] via-[#1d4c3a] to-[#101d18]", risk: "안전" },
  { id: 5, title: "평범한 아이디어를 콘텐츠로 만드는 공식", hook: "아이디어가 없는 게 아니라 관점이 없는 겁니다", score: 82, status: "보류", duration: "0:49", gradient: "from-[#7f477c] via-[#482747] to-[#181119]", risk: "유사도 높음" },
  { id: 6, title: "30일 만에 달라지는 기록 습관", hook: "하루 한 줄이면 충분합니다", score: 79, status: "렌더 중", duration: "0:28", gradient: "from-[#38658b] via-[#233d5a] to-[#10151c]", risk: "검사 중" },
];

export function ContentPage() {
  const [filter, setFilter] = useState("전체");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<number[]>([]);
  const [editing, setEditing] = useState<(typeof videos)[number] | null>(null);
  const filtered = useMemo(() => videos.filter((v) => (filter === "전체" || v.status === filter) && v.title.includes(query)), [filter, query]);
  const toggle = (id: number) => setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);

  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-[28px] font-bold tracking-tight">콘텐츠</h1><p className="mt-1 text-sm text-muted-foreground">프로젝트, 쇼츠, 소스를 한곳에서 관리하고 검토하세요.</p></div><Button><WandSparkles /> 새 프로젝트</Button></div>
    <div className="flex flex-col justify-between gap-3 rounded-2xl border border-border bg-card p-3 lg:flex-row lg:items-center"><div className="flex gap-1 overflow-auto">{["전체","검토 대기","예약됨","게시됨","보류"].map((item) => <button key={item} onClick={() => setFilter(item)} className={cn("h-8 shrink-0 rounded-lg px-3 text-xs font-semibold text-muted-foreground", filter === item && "bg-secondary text-foreground")}>{item}{item === "검토 대기" && <span className="ml-1.5 rounded-full bg-warning/15 px-1.5 text-warning">2</span>}</button>)}</div><div className="flex gap-2"><div className="relative flex-1 lg:w-64"><Search className="absolute left-3 top-2.5 size-3.5 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-9 w-full rounded-lg border border-input bg-background pl-9 pr-3 text-xs outline-none focus:border-primary" placeholder="콘텐츠 검색" /></div><Button variant="secondary" size="sm"><Filter /> 필터</Button><div className="hidden rounded-lg border border-border p-0.5 sm:flex"><button className="rounded-md bg-secondary p-1.5"><LayoutGrid className="size-3.5" /></button><button className="p-1.5 text-muted-foreground"><List className="size-3.5" /></button></div></div></div>
    {selected.length > 0 && <div className="flex flex-wrap items-center gap-2 rounded-xl border border-primary/20 bg-primary/[.06] p-3"><Badge variant="violet">{selected.length}개 선택</Badge><Button size="sm"><Check /> 승인</Button><Button size="sm" variant="secondary"><CalendarClock /> 예약</Button><Button size="sm" variant="secondary"><Download /> 내보내기</Button><Button size="sm" variant="danger"><Trash2 /> 삭제</Button><Button variant="ghost" size="sm" className="ml-auto" onClick={() => setSelected([])}>선택 해제</Button></div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{filtered.map((video) => <Card key={video.id} className={cn("group overflow-hidden transition hover:-translate-y-0.5 hover:border-primary/35", selected.includes(video.id) && "border-primary ring-1 ring-primary/30")}><CardContent className="p-0"><div className={`relative aspect-[16/10] bg-gradient-to-br ${video.gradient} noise-grid`}><button onClick={() => toggle(video.id)} aria-label={`${video.title} 선택`} className={cn("absolute left-3 top-3 z-10 grid size-5 place-items-center rounded-md border border-white/25 bg-black/30", selected.includes(video.id) && "border-primary bg-primary")} >{selected.includes(video.id) && <Check className="size-3" />}</button><Badge className="absolute right-3 top-3" variant={video.status === "검토 대기" ? "warning" : video.status === "예약됨" ? "info" : video.status === "게시됨" ? "success" : video.status === "보류" ? "danger" : "violet"}>{video.status}</Badge><div className="absolute inset-x-[18%] bottom-[23%] text-center text-base font-black leading-6 text-white"><span className="bg-black/25 px-1 backdrop-blur-sm">{video.hook}</span></div><span className="absolute bottom-3 right-3 rounded bg-black/50 px-1.5 py-0.5 font-mono text-[10px]">{video.duration}</span><button onClick={() => setEditing(video)} aria-label={`${video.title} 편집`} className="absolute inset-0 grid place-items-center bg-black/0 opacity-0 transition group-hover:bg-black/25 group-hover:opacity-100"><span className="grid size-10 place-items-center rounded-full bg-white text-black"><Play className="size-4 fill-current" /></span></button></div><div className="p-4"><div className="flex items-start gap-3"><div className={cn("grid size-10 shrink-0 place-items-center rounded-xl text-sm font-black", video.score >= 90 ? "bg-success/10 text-success" : video.score >= 84 ? "bg-primary/10 text-primary" : "bg-warning/10 text-warning")}>{video.score}</div><div className="min-w-0 flex-1"><h2 className="line-clamp-2 text-sm font-semibold leading-5">{video.title}</h2><p className="mt-1 truncate text-[10px] text-muted-foreground">훅 · 명료도 · 속도 · 안전영역 종합</p></div><button><MoreHorizontal className="size-4 text-muted-foreground" /></button></div><div className="mt-3 flex items-center justify-between border-t border-border pt-3"><span className={cn("flex items-center gap-1 text-[10px]", video.risk === "안전" ? "text-success" : video.risk === "검사 중" ? "text-muted-foreground" : "text-warning")}>{video.risk === "안전" ? <Check className="size-3" /> : <CircleAlert className="size-3" />}{video.risk}</span><Button size="sm" variant="ghost" onClick={() => setEditing(video)}>검토하기</Button></div></div></CardContent></Card>)}</div>
    {editing && <Editor video={editing} onClose={() => setEditing(null)} />}
  </div>;
}

function Editor({ video, onClose }: { video: (typeof videos)[number]; onClose: () => void }) {
  const [playing, setPlaying] = useState(false); const [saved, setSaved] = useState(false); const [tab, setTab] = useState("디자인");
  return <div className="fixed inset-0 z-[60] flex flex-col bg-[#08090d]">
    <header className="flex h-16 shrink-0 items-center gap-2 border-b border-border px-3 md:px-5"><Button variant="ghost" size="icon" onClick={onClose}><ArrowLeft /></Button><div className="min-w-0"><p className="truncate text-sm font-semibold">{video.title}</p><p className="text-[10px] text-muted-foreground">자동 저장됨 · 버전 4</p></div><div className="ml-auto flex items-center gap-1"><Button variant="ghost" size="icon"><Undo2 /></Button><Button variant="secondary" size="sm" className="hidden sm:flex">버전 기록 <ChevronDown /></Button><Button size="sm" onClick={() => setSaved(true)}>{saved ? <><Check /> 예약됨</> : <><CalendarClock /> 승인하고 예약</>}</Button><Button variant="ghost" size="icon" onClick={onClose}><X /></Button></div></header>
    <div className="grid min-h-0 flex-1 lg:grid-cols-[320px_minmax(380px,1fr)_300px]">
      <aside className="hidden min-h-0 border-r border-border bg-card lg:flex lg:flex-col"><div className="border-b border-border p-4"><h3 className="text-xs font-semibold">트랜스크립트 편집</h3><p className="mt-1 text-[10px] text-muted-foreground">텍스트를 지우면 영상 구간도 함께 잘립니다.</p><div className="relative mt-3"><Search className="absolute left-2.5 top-2.5 size-3 text-muted-foreground" /><input className="h-8 w-full rounded-lg border border-input bg-background pl-8 text-[11px] outline-none" placeholder="대본 검색" /></div></div><div className="space-y-1 overflow-auto p-3 text-xs leading-6">{[
        ["00:00", "AI 시대에 결국 살아남는 사람은 도구를 많이 아는 사람이 아닙니다."], ["00:05", "진짜 차이는 질문을 얼마나 잘 만드는지에서 시작돼요."], ["00:12", "첫째, 문제를 작은 단위로 다시 정의합니다."], ["00:19", "둘째, AI의 답을 그대로 믿지 않고 검증합니다."], ["00:26", "마지막으로 배운 것을 자신만의 맥락에 연결합니다."], ["00:31", "이 세 가지를 오늘부터 연습해 보세요."],
      ].map(([time,text], index) => <button key={time} className={cn("flex w-full gap-3 rounded-lg p-2 text-left hover:bg-accent", index === 1 && "bg-primary/10 text-foreground")}><span className="mt-1 font-mono text-[9px] text-muted-foreground">{time}</span><span>{text}</span></button>)}</div></aside>
      <main className="relative flex min-h-0 flex-col items-center justify-center overflow-hidden bg-[#0d0f14] p-5 noise-grid"><div className={`safe-area relative h-[min(64vh,620px)] aspect-[9/16] overflow-hidden rounded-2xl bg-gradient-to-br ${video.gradient} shadow-2xl`}><div className="absolute inset-x-5 top-[8%] text-center text-[10px] text-white/55">SHORTSAUTO ORIGINAL</div><div className="absolute inset-x-6 bottom-[28%] text-center text-[clamp(18px,3vh,28px)] font-black leading-[1.35] text-white">결국 살아남는 사람은<br /><span className="rounded-md bg-[#ffe453] px-2 py-0.5 text-black">질문이 다릅니다</span></div><div className="absolute bottom-6 left-5 flex items-center gap-2 text-[10px]"><span className="grid size-6 place-items-center rounded-full bg-primary font-bold">J</span>@Junlee Lab</div><button onClick={() => setPlaying(!playing)} className="absolute inset-0 grid place-items-center" aria-label={playing ? "일시정지" : "재생"}><span className="grid size-12 place-items-center rounded-full border border-white/15 bg-black/35 opacity-0 backdrop-blur transition hover:opacity-100">{playing ? <Pause className="size-4 fill-current" /> : <Play className="size-4 fill-current" />}</span></button></div><div className="mt-4 flex w-full max-w-2xl items-center gap-3 rounded-xl border border-border bg-card p-3"><button onClick={() => setPlaying(!playing)}>{playing ? <Pause className="size-4" /> : <Play className="size-4 fill-current" />}</button><span className="font-mono text-[10px] text-muted-foreground">00:12 / {video.duration}</span><div className="h-8 flex-1 overflow-hidden rounded bg-[repeating-linear-gradient(90deg,#7c5cff_0_2px,transparent_2px_6px)] opacity-50" /><Volume2 className="size-4 text-muted-foreground" /><Maximize2 className="size-4 text-muted-foreground" /></div></main>
      <aside className="hidden min-h-0 border-l border-border bg-card lg:flex lg:flex-col"><div className="flex border-b border-border p-2">{["디자인","레이아웃","오디오"].map((item) => <button key={item} onClick={() => setTab(item)} className={cn("flex-1 rounded-lg py-2 text-[11px] font-semibold text-muted-foreground", tab === item && "bg-secondary text-foreground")}>{item}</button>)}</div><div className="space-y-5 overflow-auto p-4"><div><p className="mb-2 text-xs font-semibold">자막 프리셋</p><div className="grid grid-cols-2 gap-2">{["임팩트","미니멀","뉴스","팝"].map((style, i) => <button key={style} className={cn("aspect-[4/3] rounded-xl border bg-background p-2 text-center text-[10px] font-bold", i === 0 ? "border-primary ring-1 ring-primary/20" : "border-border")}><span className={i === 0 ? "bg-[#ffe453] px-1 text-black" : ""}>{style} 자막</span></button>)}</div></div><div><p className="mb-2 text-xs font-semibold">강조 색상</p><div className="flex gap-2">{["#ffe453","#7c5cff","#2dd4bf","#ffffff","#ff4d6d"].map((color) => <button key={color} className="size-7 rounded-full border-2 border-card ring-1 ring-border" style={{background:color}} aria-label={`색상 ${color}`} />)}</div></div><div><p className="mb-2 text-xs font-semibold">품질 체크</p><div className="space-y-2 rounded-xl bg-background/55 p-3 text-[10px]"><p className="flex items-center gap-2 text-success"><Check className="size-3" /> 자막 안전영역 통과</p><p className="flex items-center gap-2 text-success"><Check className="size-3" /> 음성 라우드니스 정상</p><p className="flex items-center gap-2 text-warning"><CircleAlert className="size-3" /> 합성 미디어 표시 필요</p></div></div><Button variant="secondary" className="w-full"><Captions /> 자막 전체 편집</Button><Button variant="secondary" className="w-full"><Music2 /> 안전한 음원 선택</Button></div></aside>
    </div>
  </div>;
}
