"use client";

import { useState } from "react";
import { ArrowRight, BarChart3, Check, ChevronRight, FlaskConical, History, Lightbulb, RotateCcw, ShieldCheck, Sparkles, TrendingUp, Users, Zap } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { cn } from "@/lib/utils";

const funnel = [{label:"조회",value:"284.7K",width:100,color:"bg-primary"},{label:"3초 유지",value:"212.9K",width:78,color:"bg-[#8c74ff]"},{label:"완주",value:"108.4K",width:48,color:"bg-info"},{label:"반복 재생",value:"41.6K",width:29,color:"bg-[#2dd4bf]"},{label:"구독",value:"5.2K",width:14,color:"bg-success"}];

export function GrowthPage() {
  const [tab, setTab] = useState("인사이트"); const [experiment, setExperiment] = useState(false); const [rolledBack, setRolledBack] = useState(false);
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs text-primary"><Sparkles className="size-3.5" /> 안전한 자기개선 루프</div><h1 className="text-[28px] font-bold tracking-tight">성장 실험실</h1><p className="mt-1 text-sm text-muted-foreground">성과를 관찰하고 가설을 검증한 뒤, 충분한 근거가 있는 규칙만 승격합니다.</p></div><Button><FlaskConical /> 새 실험 만들기</Button></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["정규화 성장 점수","82.4","+9.2",TrendingUp,"text-success"],["진행 중 실험","3","표본 47개",FlaskConical,"text-primary"],["승격된 규칙","12","이번 달 +2",Zap,"text-info"],["보호된 롤백","1","유지율 가드레일",ShieldCheck,"text-warning"]].map(([label,value,detail,Icon,color]) => { const I = Icon as typeof TrendingUp; return <Card key={String(label)}><CardContent className="p-4"><div className="flex items-center justify-between"><p className="text-xs text-muted-foreground">{String(label)}</p><I className={`size-4 ${color}`} /></div><div className="mt-2 flex items-end justify-between"><p className="tabular text-2xl font-bold">{String(value)}</p><p className={`text-[10px] ${color}`}>{String(detail)}</p></div></CardContent></Card>; })}</div>
    <div className="flex gap-1 overflow-auto rounded-xl border border-border bg-card p-1">{["성과","인사이트","실험","플레이북"].map((item) => <button key={item} onClick={() => setTab(item)} className={cn("h-9 min-w-24 rounded-lg px-4 text-xs font-semibold text-muted-foreground", tab === item && "bg-secondary text-foreground")}>{item}</button>)}</div>

    {tab === "성과" && <div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><Card><CardHeader><div><CardTitle>시청 퍼널</CardTitle><CardDescription>7일 동안 12개 쇼츠의 전환 흐름</CardDescription></div></CardHeader><CardContent className="space-y-3">{funnel.map((item) => <div key={item.label}><div className="mb-1 flex items-center justify-between text-[11px]"><span className="text-muted-foreground">{item.label}</span><span className="font-mono font-semibold">{item.value}</span></div><div className="h-6 rounded-lg bg-secondary/60"><div className={`grid h-full place-items-end rounded-lg px-2 ${item.color}`} style={{width:`${item.width}%`}}><span className="text-[8px] font-semibold text-white">{item.width}%</span></div></div></div>)}</CardContent></Card><Card><CardHeader><div><CardTitle>포맷별 성과</CardTitle><CardDescription>훅·길이·자막·보이스별 기준선 대비 성과입니다.</CardDescription></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[580px] text-left text-[11px]"><thead className="text-muted-foreground"><tr className="border-b border-border"><th className="pb-3 font-medium">포맷</th><th className="pb-3 font-medium">표본</th><th className="pb-3 font-medium">3초 유지</th><th className="pb-3 font-medium">완주</th><th className="pb-3 font-medium">구독/1K</th><th className="pb-3 font-medium">성장</th></tr></thead><tbody>{[["질문형 훅 · 28~36초","28","86.2%","51.4%","22.1","+12.0%"],["숫자형 훅 · 35~45초","19","79.8%","46.3%","18.7","+5.4%"],["반전형 훅 · 20~30초","14","82.1%","49.8%","19.2","+7.1%"],["선언형 훅 · 45~60초","11","68.4%","37.1%","13.5","-4.2%"]].map((row) => <tr key={row[0]} className="border-b border-border/70"><td className="py-3 font-semibold">{row[0]}</td>{row.slice(1,-1).map((cell)=><td key={cell} className="py-3 font-mono text-muted-foreground">{cell}</td>)}<td className={`py-3 font-semibold ${row[5].startsWith("+") ? "text-success":"text-destructive"}`}>{row[5]}</td></tr>)}</tbody></table></div></CardContent></Card></div>}

    {tab === "인사이트" && <div className="grid gap-4 lg:grid-cols-3"><Insight icon={Lightbulb} title="질문형 훅이 초반 이탈을 줄여요" impact="+12%" confidence="높음" sample="쇼츠 28개" body="‘혹시 ~하고 있나요?’ 구조가 선언형 훅보다 3초 유지율을 안정적으로 높였습니다." action={experiment ? "실험에 추가됨" : "5개에 시험하기"} onAction={() => setExperiment(true)} /><Insight icon={BarChart3} title="32초 전후에서 완주율이 가장 높아요" impact="+8.4%" confidence="높음" sample="쇼츠 41개" body="28~36초 그룹이 45초 이상 그룹보다 반복 재생률과 구독 전환도 함께 높았습니다." action="길이 프리셋 만들기" /><Insight icon={Users} title="저녁 7시대에 구독 전환이 좋아요" impact="+16%" confidence="보통" sample="게시 17개" body="조회수 차이는 작지만 19:10~20:00 게시물의 구독 전환이 더 높았습니다." action="캘린더에 반영" /></div>}

    {tab === "실험" && <div className="space-y-4"><Card className="border-primary/20"><CardContent className="p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div className="flex gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><FlaskConical className="size-4" /></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold">질문형 훅 vs 선언형 훅</h2><Badge variant="violet">진행 중</Badge></div><p className="mt-1.5 text-[11px] text-muted-foreground">질문형 훅은 3초 유지율을 8% 이상 높일 것이다.</p></div></div><div className="text-right"><p className="font-mono text-lg font-bold">17 / 24</p><p className="text-[9px] text-muted-foreground">최소 표본까지 7개</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Variant label="A · 기존" title="AI 시대에 필요한 능력 3가지" metric="3초 유지 76.8%" /><Variant label="B · 후보" title="AI 때문에 불안한가요? 이것부터 바꾸세요" metric="3초 유지 87.1%" winner /></div><div className="mt-4 flex items-center gap-3"><Progress value={71} className="flex-1" /><span className="font-mono text-[10px] text-muted-foreground">71%</span></div><p className="mt-3 flex items-center gap-2 text-[10px] text-muted-foreground"><ShieldCheck className="size-3 text-success" /> 최소 표본 12개/변형, 신뢰도 90%, 정책 오류 0건을 모두 충족해야 승격됩니다.</p></CardContent></Card>{[["자막 강조색: 노랑 vs 보라","11 / 20","구독 전환","+3.1%"],["CTA 위치: 80% vs 마지막 3초","24 / 24","반복 재생","판정 중"]].map((row)=><Card key={row[0]}><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="grid size-9 place-items-center rounded-xl bg-secondary text-muted-foreground"><FlaskConical className="size-4" /></div><div className="flex-1"><p className="text-xs font-semibold">{row[0]}</p><p className="mt-1 text-[10px] text-muted-foreground">주요 지표 · {row[2]}</p></div><p className="font-mono text-xs">{row[1]}</p><Badge variant={row[3].startsWith("+")?"success":"warning"}>{row[3]}</Badge><Button variant="ghost" size="icon"><ChevronRight /></Button></CardContent></Card>)}</div>}

    {tab === "플레이북" && <div className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><Card><CardHeader><div><CardTitle>현재 적용된 성장 규칙</CardTitle><CardDescription>모든 변경은 버전과 근거를 남기며 한 번에 되돌릴 수 있습니다.</CardDescription></div><Badge variant="success">v12 활성</Badge></CardHeader><CardContent className="space-y-2">{[["훅","첫 문장을 질문형으로 시작","승인 후 실행","+12.0%"],["길이","28~36초 우선 생성","기준 충족 시 자동","+8.4%"],["자막","핵심 명사만 노랑 강조","추천만","+3.1%"],["게시","19:10~20:00 우선 예약","승인 후 실행","+16.0%"]].map((row)=><div key={row[0]} className="grid gap-2 rounded-xl border border-border bg-background/35 p-3 sm:grid-cols-[70px_1fr_120px_70px] sm:items-center"><Badge variant="neutral">{row[0]}</Badge><p className="text-xs font-semibold">{row[1]}</p><p className="text-[10px] text-muted-foreground">{row[2]}</p><p className="text-right font-mono text-[10px] text-success">{row[3]}</p></div>)}</CardContent></Card><Card className={cn("border-warning/20", rolledBack && "border-success/20")}><CardHeader><div><CardTitle>최근 변경</CardTitle><CardDescription>2026년 7월 11일 · 규칙 v12</CardDescription></div><History className="size-4 text-muted-foreground" /></CardHeader><CardContent><div className="rounded-xl bg-background/45 p-4"><p className="text-xs font-semibold">질문형 훅의 기본 가중치를 20%로 조정</p><p className="mt-2 text-[10px] leading-4 text-muted-foreground">쇼츠 28개, 채널 기준선 보정 후 3초 유지율 +12%, 완주율 +5.8%. 비용 변화 없음.</p><div className="mt-3 grid grid-cols-2 gap-2 text-center"><div className="rounded-lg bg-secondary p-2"><p className="font-mono text-xs">94%</p><p className="text-[8px] text-muted-foreground">신뢰도</p></div><div className="rounded-lg bg-secondary p-2"><p className="font-mono text-xs text-success">+8.9</p><p className="text-[8px] text-muted-foreground">정규화 점수</p></div></div></div><Button variant={rolledBack?"secondary":"danger"} className="mt-4 w-full" onClick={()=>setRolledBack(!rolledBack)}>{rolledBack?<><Check/>이전 버전으로 복구됨</>:<><RotateCcw/>v11로 되돌리기</>}</Button><p className="mt-3 text-center text-[9px] text-muted-foreground">롤백은 다음 제작부터 적용되며 기존 영상은 변경하지 않습니다.</p></CardContent></Card></div>}
  </div>;
}

function Insight({ icon: Icon, title, impact, confidence, sample, body, action, onAction }: { icon: typeof Lightbulb; title: string; impact: string; confidence: string; sample: string; body: string; action: string; onAction?:()=>void }) { return <Card className="flex flex-col"><CardHeader><div className="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-4" /></div><Badge variant="success">{impact}</Badge></CardHeader><CardContent className="flex flex-1 flex-col"><h2 className="text-sm font-bold leading-5">{title}</h2><p className="mt-2 text-[11px] leading-5 text-muted-foreground">{body}</p><div className="mt-4 flex gap-2"><Badge variant="neutral">신뢰도 {confidence}</Badge><Badge variant="neutral">{sample}</Badge></div><Button variant="secondary" className="mt-5 w-full" onClick={onAction}>{action}<ArrowRight /></Button></CardContent></Card>; }
function Variant({label,title,metric,winner}:{label:string;title:string;metric:string;winner?:boolean}) { return <div className={cn("rounded-xl border p-4", winner?"border-success/30 bg-success/[.05]":"border-border bg-background/35")}><div className="flex items-center justify-between"><Badge variant={winner?"success":"neutral"}>{label}</Badge>{winner&&<span className="flex items-center gap-1 text-[9px] font-semibold text-success"><TrendingUp className="size-3"/>현재 우세</span>}</div><p className="mt-3 text-xs font-semibold">{title}</p><p className={cn("mt-2 font-mono text-[10px]",winner?"text-success":"text-muted-foreground")}>{metric}</p></div>; }
