"use client";

import { useState } from "react";
import { Bot, Check, ChevronRight, CircleAlert, Cloud, Eye, EyeOff, KeyRound, LockKeyhole, RefreshCw, Save, ShieldCheck, Trash2, Tv, Zap } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";

export function SettingsPage() {
  const [tab,setTab]=useState("연동"); const [showKey,setShowKey]=useState(false); const [reconnected,setReconnected]=useState(false); const [saved,setSaved]=useState(false);
  return <div className="space-y-5"><div><h1 className="text-[28px] font-bold tracking-tight">연동 및 설정</h1><p className="mt-1 text-sm text-muted-foreground">채널, AI 제공자, 개인정보와 게시 안전 설정을 관리합니다.</p></div><div className="grid gap-5 lg:grid-cols-[200px_minmax(0,1fr)]"><nav className="space-y-1">{["연동","AI 제공자","게시 기본값","개인정보 및 보안","사용량"].map((item)=><button key={item} onClick={()=>setTab(item)} className={cn("flex h-10 w-full items-center justify-between rounded-[10px] px-3 text-left text-xs font-semibold text-muted-foreground",tab===item&&"bg-primary/10 text-primary")}>{item}{tab===item&&<ChevronRight className="size-3"/>}</button>)}</nav><div className="space-y-4">
      {tab==="연동"&&<><Card><CardHeader><div><div className="flex items-center gap-2"><CardTitle>YouTube 채널</CardTitle><Badge variant="success">연결됨</Badge></div><CardDescription>업로드·예약·분석에 사용하는 채널과 권한</CardDescription></div><Tv className="size-5 text-[#ff3355]"/></CardHeader><CardContent><div className="flex flex-col gap-4 rounded-xl border border-border bg-background/35 p-4 sm:flex-row sm:items-center"><div className="grid size-12 place-items-center rounded-full bg-gradient-to-br from-primary to-[#2dd4bf] text-sm font-black">JL</div><div className="flex-1"><p className="text-sm font-semibold">Junlee Lab</p><p className="mt-1 text-[10px] text-muted-foreground">채널 ID · UC••••••••2B · 구독자 48.2K</p><div className="mt-2 flex flex-wrap gap-1.5"><Badge variant="neutral">업로드</Badge><Badge variant="neutral">분석 읽기</Badge><Badge variant="neutral">채널 정보</Badge></div></div><div className="text-left sm:text-right"><p className="flex items-center gap-1 text-[10px] text-success sm:justify-end"><span className="size-1.5 rounded-full bg-success"/>토큰 정상</p><p className="mt-1 text-[9px] text-muted-foreground">마지막 동기화 8분 전</p><Button variant="secondary" size="sm" className="mt-2" onClick={()=>setReconnected(true)}>{reconnected?<><Check/>확인됨</>:<><RefreshCw/>다시 연결</>}</Button></div></div><div className="mt-3 rounded-xl border border-info/15 bg-info/[.04] p-3"><p className="text-[10px] leading-4 text-muted-foreground">업로드 전 채널, 제목, 공개 범위, 아동용 여부와 합성 미디어 표시를 항상 확인할 수 있습니다. 미검증 API 프로젝트는 비공개 업로드로 제한될 수 있어요.</p></div></CardContent></Card><Card><CardHeader><div><CardTitle>향후 채널</CardTitle><CardDescription>교차 게시 기능은 준비 상태만 표시합니다.</CardDescription></div></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Connection name="TikTok" status="준비 중"/><Connection name="Instagram Reels" status="준비 중"/></CardContent></Card></>}
      {tab==="AI 제공자"&&<><Card><CardHeader><div><CardTitle>AI Gateway</CardTitle><CardDescription>대본·장면 계획을 생성하는 모델 라우팅</CardDescription></div><Badge variant="violet">데모 모드 지원</Badge></CardHeader><CardContent className="space-y-4"><label><span className="mb-2 block text-xs font-semibold">AI_GATEWAY_API_KEY</span><div className="relative"><KeyRound className="absolute left-3 top-3 size-4 text-muted-foreground"/><input type={showKey?"text":"password"} defaultValue="vck_demo_configure_on_server" className="h-10 w-full rounded-[10px] border border-input bg-background px-10 font-mono text-xs outline-none focus:border-primary"/><button onClick={()=>setShowKey(!showKey)} className="absolute right-3 top-2.5 text-muted-foreground">{showKey?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</button></div></label><div className="grid gap-3 sm:grid-cols-2"><SettingRow icon={Bot} label="기본 모델" value="openai/gpt-5.4"/><SettingRow icon={Zap} label="실패 시 대체" value="anthropic/claude-sonnet-4.6"/></div><div className="flex gap-2"><Button variant="secondary">연결 테스트</Button><Button onClick={()=>setSaved(true)}>{saved?<><Check/>저장됨</>:<><Save/>서버 설정 저장</>}</Button></div></CardContent></Card><Card><CardContent className="p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-4 text-success"/><div><p className="text-xs font-semibold">키는 브라우저에 저장하지 않습니다</p><p className="mt-1 text-[10px] leading-4 text-muted-foreground">운영 환경에서는 Vercel OIDC를 권장하며, 비용·지연·모델·프롬프트 버전을 생성 실행별로 기록합니다.</p></div></div></CardContent></Card></>}
      {tab==="게시 기본값"&&<Card><CardHeader><div><CardTitle>게시 전 확인 항목</CardTitle><CardDescription>자동화 수준과 무관하게 정책 고위험 항목은 검토로 전환됩니다.</CardDescription></div><ShieldCheck className="size-4 text-success"/></CardHeader><CardContent className="space-y-2">{[["기본 공개 범위","일부 공개"],["아동용 콘텐츠","아니요 · 매번 확인"],["합성 미디어 표시","현실적 합성 시 필수"],["일일 최대 게시","채널당 2개"],["자동 게시 최소 점수","88점"]].map(([label,value])=><div key={label} className="flex items-center justify-between rounded-xl border border-border bg-background/35 p-3"><span className="text-xs text-muted-foreground">{label}</span><button className="flex items-center gap-2 text-xs font-semibold">{value}<ChevronRight className="size-3"/></button></div>)}</CardContent></Card>}
      {tab==="개인정보 및 보안"&&<><Card><CardHeader><div><CardTitle>개인정보 및 토큰</CardTitle><CardDescription>접근·저장·삭제 정책을 명확하게 유지합니다.</CardDescription></div><LockKeyhole className="size-4 text-muted-foreground"/></CardHeader><CardContent className="space-y-2"><SecurityRow title="OAuth 토큰 암호화" detail="AES-GCM envelope encryption · 키 버전 2" enabled/><SecurityRow title="생성 자산 출처 장부" detail="출처 URL·라이선스·생성 모델·만료일 기록" enabled/><SecurityRow title="90일 후 원본 자동 삭제" detail="게시 완료 후 원본 파일 보관 기간" enabled/><SecurityRow title="익명 제품 분석" detail="개인 콘텐츠를 모델 학습에 사용하지 않음" enabled={false}/></CardContent></Card><Card className="border-destructive/20"><CardHeader><div><CardTitle>위험 작업</CardTitle><CardDescription>삭제 후 복구할 수 없습니다.</CardDescription></div></CardHeader><CardContent className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex-1"><p className="text-xs font-semibold">워크스페이스 데이터 삭제</p><p className="mt-1 text-[10px] text-muted-foreground">원본·렌더·분석·OAuth 토큰을 모두 삭제합니다.</p></div><Button variant="danger"><Trash2/>삭제 요청</Button></CardContent></Card></>}
      {tab==="사용량"&&<Card><CardHeader><div><CardTitle>7월 사용량</CardTitle><CardDescription>생성 단계별 비용과 처리 시간을 확인합니다.</CardDescription></div><Badge variant="violet">Pro</Badge></CardHeader><CardContent className="space-y-3">{[["영상 처리","68 / 120분","57%"],["AI 생성","142 / 400회","36%"],["TTS","47 / 100분","47%"],["저장소","8.4 / 50GB","17%"]].map(([label,value,width])=><div key={label} className="rounded-xl bg-background/35 p-3"><div className="flex items-center justify-between text-xs"><span className="text-muted-foreground">{label}</span><span className="font-mono font-semibold">{value}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width}}/></div></div>)}</CardContent></Card>}
    </div></div></div>;
}
function Connection({name,status}:{name:string;status:string}){return <div className="flex items-center gap-3 rounded-xl border border-border bg-background/35 p-4"><div className="grid size-9 place-items-center rounded-xl bg-secondary text-muted-foreground"><Cloud className="size-4"/></div><div><p className="text-xs font-semibold">{name}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{status}</p></div><Badge variant="neutral" className="ml-auto">예정</Badge></div>}
function SettingRow({icon:Icon,label,value}:{icon:typeof Bot;label:string;value:string}){return <div className="flex items-center gap-3 rounded-xl border border-border bg-background/35 p-3"><Icon className="size-4 text-primary"/><div><p className="text-[9px] text-muted-foreground">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p></div></div>}
function SecurityRow({title,detail,enabled}:{title:string;detail:string;enabled:boolean}){return <div className="flex items-center gap-3 rounded-xl border border-border bg-background/35 p-3"><div className={cn("grid size-8 place-items-center rounded-lg",enabled?"bg-success/10 text-success":"bg-secondary text-muted-foreground")}>{enabled?<Check className="size-3.5"/>:<CircleAlert className="size-3.5"/>}</div><div className="flex-1"><p className="text-xs font-semibold">{title}</p><p className="mt-1 text-[9px] text-muted-foreground">{detail}</p></div><Switch checked={enabled} aria-label={title}/></div>}
